###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    database:
      image: mariadb:10.3
      container_name: api-symfony-database
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - "MYSQL_DATABASE=api-category"
        - "MYSQL_USER=admin"
        - "MYSQL_PASSWORD=123"
        - "MYSQL_ROOT_PASSWORD=123"
      ports:
        - "3306:3306"
      networks:
        - db-net

    webserver:
      image: nginx:alpine
      container_name: api-symfony-web
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      networks:
        - db-net

    php-fpm:
      build: phpdocker/php-fpm
      container_name: api-symfony-php
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - db-net
networks:
  db-net: